osx_image: xcode7.1
language: objective-c
before_install:
  - brew update
  - brew upgrade xctool
  - brew install carthage
install: true
script:
  - carthage bootstrap --verbose --platform ios
  - carthage build --verbose --platform ios --no-skip-current
